# Generated by Django 5.1.1 on 2024-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='binance_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='btc_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='eth_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ripple_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sol_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spc_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tether_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
