# Generated by Django 5.1.1 on 2024-09-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
